{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Superstore Sales\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.1380.0 (24.04)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "es-ES",
    "cultures": [
      {
        "name": "es-ES",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "9042b2d7-c18b-4871-9036-7ff17a62b39d",
        "fromColumn": "Order Date",
        "fromTable": "Superstore Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d8ffe086-224c-4eb0-8d9c-78469c6b8f24"
      }
    ],
    "sourceQueryCulture": "es-CO",
    "tables": [
      {
        "name": "Superstore Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "cc77e6ac-5d69-47dc-989c-d04702005582",
            "sourceColumn": "Order Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_d8ffe086-224c-4eb0-8d9c-78469c6b8f24"
                },
                "isDefault": true,
                "relationship": "9042b2d7-c18b-4871-9036-7ff17a62b39d"
              }
            ]
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "761d6101-1031-474c-ba5c-173e74fc8f35",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0b26a12-813a-41e4-887a-292f87eedfdb",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d83a8bb-b8a9-4d41-bc2a-8a04870c68bc",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bb41105b-0f29-4266-92e0-cc93bd773a5c",
            "sourceColumn": "Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "70d9fcd0-5307-41da-beb2-ec17f99c1053",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "169da945-1218-48a0-ac3c-f13ff61fa432",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33205f38-1981-43e1-a27d-178e6d735a41",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH('Superstore Sales'[Order Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "48e32221-f594-48d2-acf8-1a56392fe6b1",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Superstore Sales'[Order Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "dd5d14e2-a3b9-4653-8a22-556205061bc2",
            "sortByColumn": "Month Number",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Customer Segments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR TotalCustomerSales =",
              "CALCULATE(",
              "    SUM('Superstore Sales'[Sales]),",
              "    ALLEXCEPT('Superstore Sales','Superstore Sales'[Customer])",
              ")",
              "",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    TotalCustomerSales >= 60000, \"VIP\",",
              "    TotalCustomerSales >= 30000, \"Frequent\",",
              "    \"Occasional\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "c582a89d-accc-459b-af28-2c5c7b8edb9f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "1e98f10a-d2c3-4e59-84b4-ae97e9256759",
        "measures": [
          {
            "name": "Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('Superstore Sales'[Sales])",
            "lineageTag": "12aeb6b1-6087-476a-a7ba-9ecd8a72ecfd"
          },
          {
            "name": "Average Ticket",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE('Superstore Sales'[Sales])",
            "lineageTag": "b1985582-6c4e-49b6-bc8b-799ed70c53e1"
          },
          {
            "name": "Total Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('Superstore Sales'[Profit])",
            "lineageTag": "af9b6375-b050-412f-ba87-58e623b7febe"
          },
          {
            "name": "Profit Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Total Profit],[Total Sales],0)",
            "lineageTag": "35e00294-c4d5-4479-ad10-47ed5fa369f7"
          },
          {
            "name": "Monthly Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('Superstore Sales'[Sales])",
            "lineageTag": "1f2f9d64-e229-41bb-92ff-5d981d6e9124"
          },
          {
            "name": "Customer Total Spending",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Superstore Sales'[Sales]),",
              "    ALLEXCEPT('Superstore Sales','Superstore Sales'[Customer])",
              ")"
            ],
            "lineageTag": "535c3a2b-3c0c-4de0-9a2d-90c2784e0aa1"
          }
        ],
        "partitions": [
          {
            "name": "Superstore Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(File.Contents(\"C:\\Users\\victo\\Desktop\\victor\\Ing_sistemas\\semestre 8\\gestion de proyectos\\p_inteligencia de negocios\\superstore_sales (1).xlsx\"), null, true),",
                "    #\"Superstore Sales_Sheet\" = Origen{[Item=\"Superstore Sales\",Kind=\"Sheet\"]}[Data],",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(#\"Superstore Sales_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Order Date\", Int64.Type}, {\"City\", type text}, {\"Country\", type text}, {\"Category\", type text}, {\"Sales\", type number}, {\"Profit\", type number}, {\"Quantity\", Int64.Type}, {\"Customer\", type text}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_f064b75c-0c2c-4142-8fe5-6cfb5c21f404",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0c361e41-8e5b-42c2-893d-97e3db7555f5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "71326390-2d4d-482e-a17b-6f100028cd86",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ae6abfd3-1a45-490c-ab58-7b41a556ab28",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "91a9f114-0b6d-4d3d-9fbe-bb09db977f8b",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "55e17e8d-f95b-462e-b170-6f309713b935",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "0c44e363-a156-4184-9a7a-3e96648af846",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "43aacb5d-fe2b-4eb9-b296-a7030af7fd75",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "39e2dba4-7354-4dc5-b086-a0a2f126c252",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "cd8a1069-b07a-4951-9bd7-4219f938e44a",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "86d4e6fc-6d13-41a4-9ba2-5347e5060c49",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "e531660a-a175-42b7-803e-c984810e4637",
                "ordinal": 3
              }
            ],
            "lineageTag": "b40a34a2-4c99-4586-95c2-528faf8e779d"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "59f9e8fd-f791-40be-93a2-97555975cd6f",
        "partitions": [
          {
            "name": "DateTableTemplate_f064b75c-0c2c-4142-8fe5-6cfb5c21f404",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_d8ffe086-224c-4eb0-8d9c-78469c6b8f24",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "20a22a82-8edf-4d03-923e-6c9a1f72f05c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c528b4e8-41a1-4f81-b167-44fb09917303",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c6f3816a-642c-4388-b073-104abbebaa9d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "156c52a1-d9e8-44e4-85e7-77e2183b9812",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6a93b036-ddc4-4a83-9d69-58bf6350233d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "28c955d7-57d4-4ecb-86fd-e2b239113c12",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e0a440fe-4f10-47d5-8ed9-924fb93f4250",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "64b9fa29-0081-4bca-b4bf-4369104f90ca",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "c285938c-7749-4b2b-a56b-8dd5b4f4facc",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "df7bd263-66d0-4cf2-8164-ae970d01bb32",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "90102431-3a1d-45bf-83fd-0ad3076a5c5e",
                "ordinal": 3
              }
            ],
            "lineageTag": "d354d0c0-c3ff-4597-9781-74ff4cdad237"
          }
        ],
        "isHidden": true,
        "lineageTag": "c4f0218b-64c7-461d-9d41-54039f9941d1",
        "partitions": [
          {
            "name": "LocalDateTable_d8ffe086-224c-4eb0-8d9c-78469c6b8f24",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Superstore Sales'[Order Date])), 1, 1), Date(Year(MAX('Superstore Sales'[Order Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}